# Generated by Django 4.1.1 on 2022-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGENT_NAME', models.TextField(blank=True, max_length=25, null=True)),
                ('DOJ', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP_NAME', models.TextField(blank=True, max_length=25, null=True)),
                ('AGENT', models.TextField(blank=True, max_length=25, null=True)),
                ('EXAM_CODE', models.TextField(blank=True, max_length=25, null=True)),
                ('DATE', models.DateField(blank=True, null=True)),
                ('TIME', models.TimeField(null=True)),
                ('LOCATION', models.TextField(blank=True, max_length=25, null=True)),
                ('COMMENT', models.TextField(blank=True, max_length=100, null=True)),
                ('ACTUALDATE', models.DateTimeField(blank=True, null=True)),
                ('STASTUS', models.TextField(default='took', max_length=25)),
            ],
        ),
    ]
